version: '3.5'

networks:
  arc-integration:
    name: arc-integration
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/24

services:
  sbt:
    container_name: sbt
    image: mozilla/sbt:8u232_1.3.13
    networks:
      - arc-integration
    command: tail -f /dev/null
    volumes:
      - ${PWD}:/app
      - /tmp/pgp:/pgp
    working_dir: /app

  cassandra:
    image: cassandra:it
    ports:
      - 9042:9042
      - 9160:9160
    networks:
      - arc-integration
    build: cassandra/.

